apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: weather
    environment: dev
  name: weather
  namespace: dev
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: weather
      environment: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: weather
        environment: dev
    spec:
      containers:
      - env:
        - name: NGINX
          value: "http://nginx.dev.svc.cluster.local:80"
        image: nithinbenny444/testapp:v1
        imagePullPolicy: IfNotPresent
        name: weather
        ports:
        - containerPort: 5000
          protocol: TCP
        - containerPort: 5001
          protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: docker-hub
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: weather
  namespace: dev
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    name: http
  - port: 5001
    protocol: TCP
    targetPort: 5001
    name: https
  selector:
    component: weather
    environment: dev
  type: NodePort

